## Objective

At the end of this experiment you will be able to

* create arrays, vectors and matrices using Numpy
* perform operations on vectors and matrices

## Objective

At the end of this experiment you will be able to

* create arrays, vectors and matrices using Numpy
* perform operations on vectors and matrices

### Introduction to Numpy

NumPy (Numerical Python) is a Python library for scientific computing, that provide high-performance vector, matrix, and higher-dimensional data structures for Python. It is implemented in C and Fortran so when calculations are vectorized (formulated with vectors and matrices), the performance is very good.

It offers ndarray data structure for storing and ufuncs for efficiently processing the (homogeneous) data. Some of the important functionalities include: basic slicing, advanced or fancy indexing, broadcasting, etc.


**How are NumPy arrays different from Python lists?**

* Python lists are very general. They can contain any kind of object. They are dynamically typed.
* They do not support mathematical functions such as matrix and dot multiplications, etc. Implementing such functions for Python lists would not be very efficient because of the dynamic typing.
* Numpy arrays are statically typed and homogeneous. The type of the elements is determined when the array is created.
* Numpy arrays are memory efficient.
* Because of the static typing, fast implementation of mathematical functions such as multiplication and addition of numpy arrays can be implemented in a compiled language (C and Fortran is used).


Now it is time to work on practicals. Following Are the given Exercise:


#### Exercise 1: Import the numpy package under the name np

In [1]:
# Your Code Here
import numpy as np

#### Exercise 2: Create an array of 10 zeros

In [2]:
# Your Code Here
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Exercise 3: Create an array of 20 ones

In [4]:
# Your Code Here
np.ones(20)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

#### Exercise 4: Create an array of 10 fours

In [13]:
# Your Code Here
np.full((1, 10), 4)

array([[4, 4, 4, 4, 4, 4, 4, 4, 4, 4]])

#### Exercise 5: Create an array of integers from 20 to 60

In [25]:
# Your Code Here
np.arange(20, 61)

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59, 60])

#### Exercise 6: Create an array of even integers from 20 to 60

In [26]:
# Your Code Here
np.arange(20, 61, 2)

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52,
       54, 56, 58, 60])

#### Exercise 7: Create a 4 * 4 indenty matrix

In [14]:
# Your Code Here
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#### Exercise 8: Create a 3 * 3 matrix with values range from 0 to 8

In [53]:
# Your Code Here
np.arange(0, 9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Exercise 9: Generate a random number between 0 and 1 using numpy

In [79]:
# Your Code Here
np.random.rand(1)

array([0.12887914])

#### Exercise 10: Generate an array of 15 random numbers sampled from a standard normal distribution

In [80]:
# Your Code Here
np.random.randn(15)

array([ 2.62493194, -1.30325274, -0.03604511,  0.82878254,  0.63443505,
       -2.49158068, -0.56875479,  0.10995934,  0.96056489, -1.16709339,
        1.58735641, -0.45610857, -1.13303208, -0.3633442 ,  0.61255899])

#### Exercise 11: Create a vector with values ranging from 10 to 49 

In [54]:
# Your Code Here
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### Exercise 12: Create a numpy array from a List

In [58]:
# Your Code Here
l = list([1, 2])
np.array(l)

array([1, 2])

#### Exercise 13: Find indices of non-zero elements from [122,233,0,0,44,3]

In [49]:
# Your Code Here
A = np.array([122, 233, 0, 0, 44, 3])
np.nonzero(A)

(array([0, 1, 4, 5]),)

#### Exercise 14:  Create a 3 * 3 * 3 array with random values

In [62]:
# Your Code Here
np.random.random((3, 3, 3))

array([[[0.87193351, 0.82877218, 0.20468235],
        [0.58024985, 0.23567812, 0.42426092],
        [0.90568684, 0.08320114, 0.52669014]],

       [[0.91939623, 0.18659368, 0.24114731],
        [0.34164487, 0.48703557, 0.7965522 ],
        [0.05966584, 0.93691351, 0.33768403]],

       [[0.77545193, 0.57468181, 0.20750816],
        [0.45428375, 0.65784361, 0.54225569],
        [0.02484521, 0.56878259, 0.20956919]]])

#### Exercise 15: Create a 10 * 10 array with random values and find the minimum and maximum values

In [81]:
# Your Code Here
A = np.random.random((10, 10))
A, A.max(), A.min()

(array([[0.03744232, 0.22883512, 0.40329235, 0.2075304 , 0.61793919,
         0.5690668 , 0.84404688, 0.99503208, 0.05397294, 0.92403585],
        [0.72921753, 0.691565  , 0.50231053, 0.86423909, 0.33022041,
         0.11565628, 0.15083561, 0.68952389, 0.63742741, 0.79471977],
        [0.62223266, 0.61053565, 0.58771557, 0.60355852, 0.21282943,
         0.39887538, 0.70652666, 0.13085393, 0.00815694, 0.87157094],
        [0.39096711, 0.82022367, 0.99441714, 0.86366481, 0.17230314,
         0.67371385, 0.67922306, 0.88688818, 0.85533542, 0.82855153],
        [0.23193253, 0.5773159 , 0.13802264, 0.54248668, 0.95169754,
         0.93220888, 0.24901707, 0.38081378, 0.12843106, 0.12147064],
        [0.7900239 , 0.45556484, 0.42556314, 0.83851802, 0.44578575,
         0.18162091, 0.93281492, 0.75035435, 0.94982308, 0.37232273],
        [0.53096885, 0.70633881, 0.04043191, 0.37488379, 0.57993333,
         0.39117645, 0.12786254, 0.44073458, 0.79547588, 0.97321632],
        [0.62527201, 0.8197

#### Exercise 16: Create a random vector of size 10 and find the mean value

In [83]:
# Your Code Here
A = np.random.randn(10)
A, A.mean()

(array([ 0.08725926,  1.81930807, -0.010923  ,  0.09334741,  0.69947784,
         1.09467968, -0.04515601, -1.04812519, -1.26380027,  0.17629829]),
 0.1602366067932497)

#### Exercise 17:  Create a checkerboard 8 * 8 matrix using the tile function 

In [88]:
# Your Code Here
np.tile(np.eye(2), (4, 4))

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

#### Exercise 18: Given two arrays *A* and *B*, perform the below operations.

* A + B
* A - B
* A * B
* A / B
* A ** 3

A = np.arange(1,6)

B = np.arange(6,15, 2)

In [89]:
# Your Code Here
A = np.arange(1, 6)
B = np.arange(6, 15, 2)
#A
#B
print(A+B)
print(A-B)
print(A*B)
print(A/B)
print(A**3)


[ 7 10 13 16 19]
[-5 -6 -7 -8 -9]
[ 6 16 30 48 70]
[0.16666667 0.25       0.3        0.33333333 0.35714286]
[  1   8  27  64 125]


#### Exercise 19: Given an Array *A*. Calculate the square root of elements in it.

A = np.arange(1,20, 2)

In [44]:
# Your Code Here
A = np.arange(1, 20, 2)
np.sqrt(A)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

#### Exercise 20: Given an array *A*. Calculate the exponential of elements in it.

A = np.arange(1, 20, 2)

In [77]:
# Your Code Here
A = np.arange(1, 20, 2)
A, np.exp(A)

(array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19]),
 array([2.71828183e+00, 2.00855369e+01, 1.48413159e+02, 1.09663316e+03,
        8.10308393e+03, 5.98741417e+04, 4.42413392e+05, 3.26901737e+06,
        2.41549528e+07, 1.78482301e+08]))